//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResBilling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_role_func
    {
        public int Id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> func_id { get; set; }
        public Nullable<int> createdBy { get; set; }
        public string createdDate { get; set; }
    
        public virtual auth_functions auth_functions { get; set; }
        public virtual auth_roles auth_roles { get; set; }
    }
}
