//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResBilling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_temp_bill
    {
        public int Id { get; set; }
        public Nullable<int> proId { get; set; }
        public Nullable<int> ticketId { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> proDiscount { get; set; }
    
        public virtual db_product db_product { get; set; }
        public virtual bill_ticket bill_ticket { get; set; }
    }
}
