//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResBilling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill_ticket()
        {
            this.bill_temp_bill = new HashSet<bill_temp_bill>();
        }
    
        public int Id { get; set; }
        public Nullable<int> tbl_id { get; set; }
        public Nullable<int> billing_type { get; set; }
        public Nullable<int> cus_id { get; set; }
        public Nullable<int> stewardId { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> total_discount { get; set; }
        public Nullable<int> is_hold { get; set; }
        public Nullable<int> created_by { get; set; }
        public string created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_temp_bill> bill_temp_bill { get; set; }
        public virtual db_employee db_employee { get; set; }
        public virtual my_tables my_tables { get; set; }
        public virtual db_customer db_customer { get; set; }
    }
}
