//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResBilling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_customer()
        {
            this.bill_ticket = new HashSet<bill_ticket>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string nic { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public Nullable<int> cusType { get; set; }
        public Nullable<int> createdBy { get; set; }
        public string createdDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_ticket> bill_ticket { get; set; }
        public virtual db_cus_type db_cus_type { get; set; }
    }
}
