//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResBilling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_product()
        {
            this.bill_temp_bill = new HashSet<bill_temp_bill>();
            this.db_inv_direct_sell_stock = new HashSet<db_inv_direct_sell_stock>();
            this.db_inv_raw_stock = new HashSet<db_inv_raw_stock>();
            this.db_price = new HashSet<db_price>();
            this.db_real_time_direct_sell_stock = new HashSet<db_real_time_direct_sell_stock>();
            this.db_real_time_raw_stock = new HashSet<db_real_time_raw_stock>();
        }
    
        public int Id { get; set; }
        public string pro_code { get; set; }
        public string pro_barcode { get; set; }
        public string pro_name { get; set; }
        public Nullable<int> pro_cat_id { get; set; }
        public Nullable<int> stock_cat_id { get; set; }
        public Nullable<int> created_by { get; set; }
        public string created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_temp_bill> bill_temp_bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_inv_direct_sell_stock> db_inv_direct_sell_stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_inv_raw_stock> db_inv_raw_stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_price> db_price { get; set; }
        public virtual db_pro_category db_pro_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_real_time_direct_sell_stock> db_real_time_direct_sell_stock { get; set; }
        public virtual db_stock_cat db_stock_cat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_real_time_raw_stock> db_real_time_raw_stock { get; set; }
    }
}
