//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResBilling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_price
    {
        public int Id { get; set; }
        public Nullable<int> pro_id { get; set; }
        public Nullable<double> buying_price { get; set; }
        public Nullable<double> selling_price { get; set; }
        public Nullable<double> profit { get; set; }
        public Nullable<double> discount { get; set; }
    
        public virtual db_product db_product { get; set; }
    }
}
