//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResBilling.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PosDBEntitiesBill : DbContext
    {
        public PosDBEntitiesBill()
            : base("name=PosDBEntitiesBill")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auth_functions> auth_functions { get; set; }
        public virtual DbSet<auth_role_func> auth_role_func { get; set; }
        public virtual DbSet<auth_roles> auth_roles { get; set; }
        public virtual DbSet<auth_users> auth_users { get; set; }
        public virtual DbSet<bill_temp_bill> bill_temp_bill { get; set; }
        public virtual DbSet<bill_ticket> bill_ticket { get; set; }
        public virtual DbSet<db_cus_type> db_cus_type { get; set; }
        public virtual DbSet<db_customer> db_customer { get; set; }
        public virtual DbSet<db_emp_type> db_emp_type { get; set; }
        public virtual DbSet<db_employee> db_employee { get; set; }
        public virtual DbSet<db_inv_direct_sell_stock> db_inv_direct_sell_stock { get; set; }
        public virtual DbSet<db_inv_raw_stock> db_inv_raw_stock { get; set; }
        public virtual DbSet<db_price> db_price { get; set; }
        public virtual DbSet<db_pro_category> db_pro_category { get; set; }
        public virtual DbSet<db_product> db_product { get; set; }
        public virtual DbSet<db_real_time_direct_sell_stock> db_real_time_direct_sell_stock { get; set; }
        public virtual DbSet<db_real_time_raw_stock> db_real_time_raw_stock { get; set; }
        public virtual DbSet<db_stk_invoice> db_stk_invoice { get; set; }
        public virtual DbSet<db_stock> db_stock { get; set; }
        public virtual DbSet<db_stock_cat> db_stock_cat { get; set; }
        public virtual DbSet<db_supplier> db_supplier { get; set; }
        public virtual DbSet<my_tables> my_tables { get; set; }
        public virtual DbSet<sys_forms> sys_forms { get; set; }
    }
}
