//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace res_pos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_users
    {
        public int Id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
    
        public virtual auth_roles auth_roles { get; set; }
        public virtual db_employee db_employee { get; set; }
    }
}
