//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace res_pos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_customer
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string nic { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public Nullable<int> cusType { get; set; }
        public Nullable<int> createdBy { get; set; }
        public string createdDate { get; set; }
    
        public virtual db_cus_type db_cus_type { get; set; }
    }
}
